### ISSUE TITLE
not really an issue

### ISSUE THREAD

**Issue by Justinneumann01** [Robinhuett/sbuscontroller#1]
Hey mate not really an issue. ive got a genuine arduino uno and trying to get this to work. What board settings do i need to upload this i keep getting the following error when i go to compile.

Arduino: 1.8.5 (Windows 10), TD: 1.41, Board: "Arduino/Genuino Uno"

Build options changed, rebuilding all
In file included from C:\Users\Justin\Desktop\sbuscontroller-master\sbuscontroller\sbuscontroller.ino:8:0:

C:\Program Files (x86)\Arduino\libraries\Joystick\src/Joystick.h:32:2: error: #error The Joystick library can only be used with a USB MCU (e.g. Arduino Leonardo, Arduino Micro, etc.).

 #error The Joystick library can only be used with a USB MCU (e.g. Arduino Leonardo, Arduino Micro, etc.).

  ^

exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by rbnis** [comment]
Hi @Justinneumann01 
this is one of the pit falls with this project. Just like the error message states you have to use a board with an USB MCU like the Leonardo or Micro boards. For example this one: https://store.arduino.cc/usa/arduino-micro

The difference is the 32u4, which is recognizable as an USB HID device.

**Comment by wdcossey** [comment]
If you are stuck with a Uno board have a look at [vJoySerialFeeder](https://github.com/Cleric-K/vJoySerialFeeder)
